name: 🥼

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coveralls:
    name: Run coverage checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
            sudo apt-get update
            pip install --upgrade pip
            pip install pytest numpy scipy coverage coveralls pytest-cov pytest-xdist
        name: Install dependencies
      - uses: actions/checkout@v2
      - run: python3 -m pip install -r requirements.txt
        name: Install requirements.txt
      - run: |
            sudo apt-get install -y libeigen3-dev libopenblas-dev liblapack-dev ninja-build
            pip install pybind11
            git clone https://github.com/FEniCS/basix.git basix-src
            cd basix-src
            cmake -G Ninja -B build-dir -S .
            cmake --build build-dir
            sudo cmake --install build-dir
            pip install ./python/
        name: Install basix
      - run: python3 -m pytest -n=auto --cov=symfem --durations=50 test/
        name: Run unit tests
        continue-on-error: true
      - name: Upload to Coveralls
        if: ${{ github.repository == 'mscroggs/symfem' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.coverall_token }}
        run: coveralls
