on:
  push

jobs:
  style-checks:
    name: Run style checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y python3-setuptools
      - run: pip3 install pydocstyle flake8
      - run: |
            python3 -m flake8 .
        name: Run flake8 checks
      - run: python3 -m pydocstyle feast
        name: Run pydocstyle checks

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y python3-setuptools libeigen3-dev python3-pytest python3-numpy python3-flake8 python3-sympy
        name: Install dependencies
      - run: |
            cd /usr/include
            sudo ln -sf eigen3/Eigen Eigen
        name: Fix eigen location
      - uses: actions/checkout@v2
      - run: pip3 install -r requirements.txt
        name: Install requirements.txt
      - run: |
            wget -nc --quiet https://github.com/pybind/pybind11/archive/v2.5.0.tar.gz
            tar -xf v2.5.0.tar.gz
            cd pybind11-2.5.0
            mkdir build && cd build
            cmake -DPYBIND11_TEST=off .. && sudo make install
            cd ../..
            git clone https://github.com/FEniCS/libtab.git libtab-src
            cd libtab-src
            mkdir build
            cd build
            cmake ../cpp
            make
            sudo ln -sf libtab.so /usr/local/lib/
            sudo ln -sf libtab.cpython-38-x86_64-linux-gnu.so /usr/local/lib/python3.8/dist-packages/
        name: Install libtab
      - run: python3 -m pytest --durations=50 test
        name: Run unit tests
