on:
  push

jobs:
  style-checks:
    name: Run style checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y python3-setuptools
      - run: pip3 install pydocstyle flake8
      - run: |
            python3 -m flake8 .
        name: Run flake8 checks
      - run: python3 -m pydocstyle feast
        name: Run pydocstyle checks

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y python3-setuptools
      - uses: actions/checkout@v2
      - run: pip3 install -r requirements.txt
        name: Install requirements
      - run: |
            sudo apt-get install -y libeigen3-dev
            git clone https://github.com/FEniCS/libtab.git
            cd libtab
            mkdir build
            cd build
            cmake -I /usr/include/eigen3 ../cpp
            make
            sudo make install
        name: Install libtab
      - run: pip3 install pytest
        name: Install pytest
      - run: python3 -m pytest --durations=50 test
        name: Run unit tests
