on:
  push:
  schedule:
    - cron: "0 7 * * 1"

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
            sudo apt-get update
            sudo apt-get install -y libeigen3-dev
            pip install --upgrade pip
            pip install scikit-build pytest numpy
        name: Install dependencies
      - uses: actions/checkout@v2
      - run: python3 -m pip install -r requirements.txt
        name: Install requirements.txt
      - run: |
            git clone https://github.com/FEniCS/libtab.git@mscroggs/dq libtab-src
            cd libtab-src
            pip install .
        name: Install libtab
      - run: python3 -m pytest --durations=50 test
        name: Run unit tests
